FROM oven/bun:1 AS base
WORKDIR /app

COPY package.json bun.lock ./
COPY apps/backend/package.json ./apps/backend/
COPY apps/frontend/package.json ./apps/frontend/
RUN bun install --filter finanzas-personales-backend --frozen-lockfile

COPY apps/backend ./apps/backend
WORKDIR /app/apps/backend

ENV DATABASE_URL="postgresql://user:pass@localhost:5432/db"
RUN bunx prisma generate

COPY apps/backend/entrypoint.sh .
RUN chmod +x entrypoint.sh

EXPOSE 3000
ENTRYPOINT ["./entrypoint.sh"]
