#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  DO \$\$
  BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${POSTGRES_APP_USER}') THEN
      CREATE ROLE ${POSTGRES_APP_USER} WITH LOGIN PASSWORD '${POSTGRES_APP_PASSWORD}';
    END IF;
  END
  \$\$;

  DO \$\$
  BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${POSTGRES_MIGRATION_USER}') THEN
      CREATE ROLE ${POSTGRES_MIGRATION_USER} WITH LOGIN PASSWORD '${POSTGRES_MIGRATION_PASSWORD}';
    END IF;
  END
  \$\$;

  GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_APP_USER};
  GRANT USAGE ON SCHEMA public TO ${POSTGRES_APP_USER};
  GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ${POSTGRES_APP_USER};
  GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO ${POSTGRES_APP_USER};

  ALTER DEFAULT PRIVILEGES FOR ROLE ${POSTGRES_MIGRATION_USER} IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${POSTGRES_APP_USER};
  ALTER DEFAULT PRIVILEGES FOR ROLE ${POSTGRES_MIGRATION_USER} IN SCHEMA public
    GRANT USAGE, SELECT ON SEQUENCES TO ${POSTGRES_APP_USER};

  GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_MIGRATION_USER};
  GRANT ALL PRIVILEGES ON SCHEMA public TO ${POSTGRES_MIGRATION_USER};
  GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ${POSTGRES_MIGRATION_USER};
  GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ${POSTGRES_MIGRATION_USER};

  ALTER DEFAULT PRIVILEGES FOR ROLE ${POSTGRES_MIGRATION_USER} IN SCHEMA public
    GRANT ALL PRIVILEGES ON TABLES TO ${POSTGRES_MIGRATION_USER};
  ALTER DEFAULT PRIVILEGES FOR ROLE ${POSTGRES_MIGRATION_USER} IN SCHEMA public
    GRANT ALL PRIVILEGES ON SEQUENCES TO ${POSTGRES_MIGRATION_USER};
EOSQL
