#!/bin/bash
set -e

DB_HOST="${DB_HOST:-localhost}"
DB_PORT="${DB_PORT:-5432}"

echo "→ Creando usuarios de BD en servidor existente (${DB_HOST}:${DB_PORT})..."

export PGPASSWORD="${POSTGRES_PASSWORD}"

psql -h "$DB_HOST" -p "$DB_PORT" -U "${POSTGRES_USER}" -d "${POSTGRES_DB}" -v ON_ERROR_STOP=1 <<-EOSQL
  DO \$\$
  BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${POSTGRES_APP_USER}') THEN
      CREATE ROLE ${POSTGRES_APP_USER} WITH LOGIN PASSWORD '${POSTGRES_APP_PASSWORD}';
      RAISE NOTICE 'Usuario % creado', '${POSTGRES_APP_USER}';
    ELSE
      RAISE NOTICE 'Usuario % ya existe', '${POSTGRES_APP_USER}';
    END IF;
  END
  \$\$;

  DO \$\$
  BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${POSTGRES_MIGRATION_USER}') THEN
      CREATE ROLE ${POSTGRES_MIGRATION_USER} WITH LOGIN PASSWORD '${POSTGRES_MIGRATION_PASSWORD}';
      RAISE NOTICE 'Usuario % creado', '${POSTGRES_MIGRATION_USER}';
    ELSE
      RAISE NOTICE 'Usuario % ya existe', '${POSTGRES_MIGRATION_USER}';
    END IF;
  END
  \$\$;

  GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_APP_USER};
  GRANT USAGE ON SCHEMA public TO ${POSTGRES_APP_USER};
  GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ${POSTGRES_APP_USER};
  GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO ${POSTGRES_APP_USER};

  ALTER DEFAULT PRIVILEGES FOR ROLE ${POSTGRES_MIGRATION_USER} IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${POSTGRES_APP_USER};
  ALTER DEFAULT PRIVILEGES FOR ROLE ${POSTGRES_MIGRATION_USER} IN SCHEMA public
    GRANT USAGE, SELECT ON SEQUENCES TO ${POSTGRES_APP_USER};

  GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_MIGRATION_USER};
  GRANT ALL PRIVILEGES ON SCHEMA public TO ${POSTGRES_MIGRATION_USER};
  GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ${POSTGRES_MIGRATION_USER};
  GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ${POSTGRES_MIGRATION_USER};

  ALTER DEFAULT PRIVILEGES FOR ROLE ${POSTGRES_MIGRATION_USER} IN SCHEMA public
    GRANT ALL PRIVILEGES ON TABLES TO ${POSTGRES_MIGRATION_USER};
  ALTER DEFAULT PRIVILEGES FOR ROLE ${POSTGRES_MIGRATION_USER} IN SCHEMA public
    GRANT ALL PRIVILEGES ON SEQUENCES TO ${POSTGRES_MIGRATION_USER};
EOSQL

echo "✓ Usuarios configurados correctamente."
