/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardSuscripcionesRouteImport } from './routes/dashboard/suscripciones'
import { Route as DashboardPerfilRouteImport } from './routes/dashboard/perfil'
import { Route as DashboardIngresosRouteImport } from './routes/dashboard/ingresos'
import { Route as DashboardGastosRouteImport } from './routes/dashboard/gastos'
import { Route as DashboardFormasDePagoRouteImport } from './routes/dashboard/formas-de-pago'
import { Route as DashboardEntidadesFinancierasRouteImport } from './routes/dashboard/entidades-financieras'
import { Route as DashboardCategoriasRouteImport } from './routes/dashboard/categorias'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSuscripcionesRoute = DashboardSuscripcionesRouteImport.update({
  id: '/suscripciones',
  path: '/suscripciones',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPerfilRoute = DashboardPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIngresosRoute = DashboardIngresosRouteImport.update({
  id: '/ingresos',
  path: '/ingresos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGastosRoute = DashboardGastosRouteImport.update({
  id: '/gastos',
  path: '/gastos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFormasDePagoRoute = DashboardFormasDePagoRouteImport.update({
  id: '/formas-de-pago',
  path: '/formas-de-pago',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEntidadesFinancierasRoute =
  DashboardEntidadesFinancierasRouteImport.update({
    id: '/entidades-financieras',
    path: '/entidades-financieras',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardCategoriasRoute = DashboardCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/categorias': typeof DashboardCategoriasRoute
  '/dashboard/entidades-financieras': typeof DashboardEntidadesFinancierasRoute
  '/dashboard/formas-de-pago': typeof DashboardFormasDePagoRoute
  '/dashboard/gastos': typeof DashboardGastosRoute
  '/dashboard/ingresos': typeof DashboardIngresosRoute
  '/dashboard/perfil': typeof DashboardPerfilRoute
  '/dashboard/suscripciones': typeof DashboardSuscripcionesRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/categorias': typeof DashboardCategoriasRoute
  '/dashboard/entidades-financieras': typeof DashboardEntidadesFinancierasRoute
  '/dashboard/formas-de-pago': typeof DashboardFormasDePagoRoute
  '/dashboard/gastos': typeof DashboardGastosRoute
  '/dashboard/ingresos': typeof DashboardIngresosRoute
  '/dashboard/perfil': typeof DashboardPerfilRoute
  '/dashboard/suscripciones': typeof DashboardSuscripcionesRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/categorias': typeof DashboardCategoriasRoute
  '/dashboard/entidades-financieras': typeof DashboardEntidadesFinancierasRoute
  '/dashboard/formas-de-pago': typeof DashboardFormasDePagoRoute
  '/dashboard/gastos': typeof DashboardGastosRoute
  '/dashboard/ingresos': typeof DashboardIngresosRoute
  '/dashboard/perfil': typeof DashboardPerfilRoute
  '/dashboard/suscripciones': typeof DashboardSuscripcionesRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/categorias'
    | '/dashboard/entidades-financieras'
    | '/dashboard/formas-de-pago'
    | '/dashboard/gastos'
    | '/dashboard/ingresos'
    | '/dashboard/perfil'
    | '/dashboard/suscripciones'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/categorias'
    | '/dashboard/entidades-financieras'
    | '/dashboard/formas-de-pago'
    | '/dashboard/gastos'
    | '/dashboard/ingresos'
    | '/dashboard/perfil'
    | '/dashboard/suscripciones'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/categorias'
    | '/dashboard/entidades-financieras'
    | '/dashboard/formas-de-pago'
    | '/dashboard/gastos'
    | '/dashboard/ingresos'
    | '/dashboard/perfil'
    | '/dashboard/suscripciones'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/suscripciones': {
      id: '/dashboard/suscripciones'
      path: '/suscripciones'
      fullPath: '/dashboard/suscripciones'
      preLoaderRoute: typeof DashboardSuscripcionesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/perfil': {
      id: '/dashboard/perfil'
      path: '/perfil'
      fullPath: '/dashboard/perfil'
      preLoaderRoute: typeof DashboardPerfilRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ingresos': {
      id: '/dashboard/ingresos'
      path: '/ingresos'
      fullPath: '/dashboard/ingresos'
      preLoaderRoute: typeof DashboardIngresosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/gastos': {
      id: '/dashboard/gastos'
      path: '/gastos'
      fullPath: '/dashboard/gastos'
      preLoaderRoute: typeof DashboardGastosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/formas-de-pago': {
      id: '/dashboard/formas-de-pago'
      path: '/formas-de-pago'
      fullPath: '/dashboard/formas-de-pago'
      preLoaderRoute: typeof DashboardFormasDePagoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/entidades-financieras': {
      id: '/dashboard/entidades-financieras'
      path: '/entidades-financieras'
      fullPath: '/dashboard/entidades-financieras'
      preLoaderRoute: typeof DashboardEntidadesFinancierasRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/categorias': {
      id: '/dashboard/categorias'
      path: '/categorias'
      fullPath: '/dashboard/categorias'
      preLoaderRoute: typeof DashboardCategoriasRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardRouteChildren {
  DashboardCategoriasRoute: typeof DashboardCategoriasRoute
  DashboardEntidadesFinancierasRoute: typeof DashboardEntidadesFinancierasRoute
  DashboardFormasDePagoRoute: typeof DashboardFormasDePagoRoute
  DashboardGastosRoute: typeof DashboardGastosRoute
  DashboardIngresosRoute: typeof DashboardIngresosRoute
  DashboardPerfilRoute: typeof DashboardPerfilRoute
  DashboardSuscripcionesRoute: typeof DashboardSuscripcionesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCategoriasRoute: DashboardCategoriasRoute,
  DashboardEntidadesFinancierasRoute: DashboardEntidadesFinancierasRoute,
  DashboardFormasDePagoRoute: DashboardFormasDePagoRoute,
  DashboardGastosRoute: DashboardGastosRoute,
  DashboardIngresosRoute: DashboardIngresosRoute,
  DashboardPerfilRoute: DashboardPerfilRoute,
  DashboardSuscripcionesRoute: DashboardSuscripcionesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
